### ISSUE TITLE
Does not find module in the crate

### ISSUE THREAD

**Issue by caseyc37** [xiallc/pixie_sdk#1]
Running my code with a prior version of the Pixie SDK, and the code works. It connects to the hardware, reads data from the hardware, and all of that.

Running with 3.0.0, I get the following output in the logfile:

```
[INFO ] 2021-08-30T11:06:02.934877 begin log
[INFO ] 2021-08-30T11:06:02.948905 Pixie16InitSystem: NumModules=1 PXISlotMap=0x55dcf8c439a0 OfflineMode=0
[INFO ] 2021-08-30T11:06:02.948950 crate: initialise
[INFO ] 2021-08-30T11:06:02.949157 module: PLX: driver: version=8.2.3
[INFO ] 2021-08-30T11:06:02.949191 module: PLX: device: type=9054 rev=172
[INFO ] 2021-08-30T11:06:02.949274 module: PLX: pci: device-number=0 domain=0 bus=6 slot=15
[ERROR] 2021-08-30T11:06:02.949372 error(except): pcf8574::read_a_byte: no ACK after DevSel
[ERROR] 2021-08-30T11:06:02.963314 module: device 0: error: pcf8574::read_a_byte: no ACK after DevSel
[INFO ] 2021-08-30T11:06:02.963408 module offline: device 0
[ERROR] 2021-08-30T11:06:02.963600 error(except): module: num=-1,slot=0: PCI find: device: 1: PLX (517) PLX_STATUS_INVALID_OBJECT
[ERROR] 2021-08-30T11:06:02.963661 module: device 1: error: module: num=-1,slot=0: PCI find: device: 1: PLX (517) PLX_STATUS_INVALID_OBJECT
[ERROR] 2021-08-30T11:06:02.963711 error(except): Crate did not initialize with any modules.
[ERROR] 2021-08-30T11:06:02.963764 result=201, Crate did not initialize with any modules.
```

For some reason, it seems that the SDK is simply not seeing the module. Yet the module is physically there, and is found by a previous version of the SDK.

**Comment by caseyc37** [comment]
I am linking against libPixie16Api.so.  My module has a sticker that says S/N 219 - I assume that's the serial number you need. The crate - hmmm. The crate has "Made in Germany by Plein & Baus GmbH" printed on it. Not sure if that helps.

**Comment by xia-stan** [comment]
After further discussion we found that the crate in question has an ELMA backplane. Based on our tests, this backplane doesn't support automatic slot identification. I will put in an internal ticket to see if we can find a way to support this. 

For now, the recommended solution is to to use the original C API.
